INSERT INTO  biz_catalog (id,name,parent_id,attributes,type) VALUES(0,'手机数码',null,'','FRONTEND');
INSERT INTO  biz_catalog (id,name,parent_id,attributes,type) VALUES(1,'华为',0,'','FRONTEND');
INSERT INTO  biz_catalog (id,name,parent_id,attributes,type) VALUES(2,'苹果',0,'','FRONTEND');
INSERT INTO  biz_catalog (id,name,parent_id,attributes,type) VALUES(3,'小米',0,'','FRONTEND');
INSERT INTO  biz_catalog (id,name,parent_id,attributes,type) VALUES(4,'三星',0,'','FRONTEND');
INSERT INTO  biz_catalog (id,name,parent_id,attributes,type) VALUES(5,'平板电脑',null,'','FRONTEND');
INSERT INTO  biz_catalog (id,name,parent_id,attributes,type) VALUES(6,'华为',5,'','FRONTEND');
INSERT INTO  biz_catalog (id,name,parent_id,attributes,type) VALUES(7,'苹果',5,'','FRONTEND');
INSERT INTO  biz_catalog (id,name,parent_id,attributes,type) VALUES(8,'小米',5,'','FRONTEND');
INSERT INTO  biz_catalog (id,name,parent_id,attributes,type) VALUES(9,'三星',5,'','FRONTEND');
INSERT INTO  biz_catalog (id,name,parent_id,attributes,type) VALUES(10,'台式电脑',null,'','FRONTEND');
INSERT INTO  biz_catalog (id,name,parent_id,attributes,type) VALUES(11,'华为',10,'','FRONTEND');
INSERT INTO  biz_catalog (id,name,parent_id,attributes,type) VALUES(12,'苹果',10,'','FRONTEND');
INSERT INTO  biz_catalog (id,name,parent_id,attributes,type) VALUES(13,'小米',10,'','FRONTEND');
INSERT INTO  biz_catalog (id,name,parent_id,attributes,type) VALUES(14,'三星',10,'','FRONTEND');

INSERT INTO  biz_catalog (id,name,parent_id,attributes,type) VALUES(15,'华为',null,'品牌:华为','BACKEND');
INSERT INTO  biz_catalog (id,name,parent_id,attributes,type) VALUES(16,'苹果',null,'品牌:苹果','BACKEND');
INSERT INTO  biz_catalog (id,name,parent_id,attributes,type) VALUES(17,'小米',null,'品牌:小米','BACKEND');
INSERT INTO  biz_catalog (id,name,parent_id,attributes,type) VALUES(18,'三星',null,'品牌:三星','BACKEND');
INSERT INTO  biz_catalog (id,name,parent_id,attributes,type) VALUES(19,'手机数码',15,'分类:手机','BACKEND');
INSERT INTO  biz_catalog (id,name,parent_id,attributes,type) VALUES(21,'台式电脑',15,'分类:台式','BACKEND');
INSERT INTO  biz_catalog (id,name,parent_id,attributes,type) VALUES(22,'手机数码',16,'分类:手机','BACKEND');
INSERT INTO  biz_catalog (id,name,parent_id,attributes,type) VALUES(23,'平板电脑',16,'分类:平板','BACKEND');
INSERT INTO  biz_catalog (id,name,parent_id,attributes,type) VALUES(24,'台式电脑',16,'分类:台式','BACKEND');
INSERT INTO  biz_catalog (id,name,parent_id,attributes,type) VALUES(31,'无线耳机',16,'分类:无线耳机','BACKEND');
INSERT INTO  biz_catalog (id,name,parent_id,attributes,type) VALUES(25,'手机数码',17,'分类:手机','BACKEND');
INSERT INTO  biz_catalog (id,name,parent_id,attributes,type) VALUES(26,'平板电脑',17,'分类:平板','BACKEND');
INSERT INTO  biz_catalog (id,name,parent_id,attributes,type) VALUES(27,'台式电脑',17,'分类:台式','BACKEND');
INSERT INTO  biz_catalog (id,name,parent_id,attributes,type) VALUES(28,'手机数码',18,'分类:手机','BACKEND');
INSERT INTO  biz_catalog (id,name,parent_id,attributes,type) VALUES(29,'平板电脑',18,'分类:平板','BACKEND');
INSERT INTO  biz_catalog (id,name,parent_id,attributes,type) VALUES(30,'智能电视',18,'分类:智能电视','BACKEND');
INSERT INTO  biz_catalog (id,name,parent_id,attributes,type) VALUES(32,'60寸',30,'屏幕尺寸:60英尺','BACKEND');
INSERT INTO  biz_catalog (id,name,parent_id,attributes,type) VALUES(33,'50寸',30,'屏幕尺寸:50英尺','BACKEND');
INSERT INTO  biz_catalog (id,name,parent_id,attributes,type) VALUES(34,'40寸',30,'屏幕尺寸:40英尺','BACKEND');
INSERT INTO  biz_catalog (id,name,parent_id,attributes,type) VALUES(35,'笔记本电脑',16,'品牌:苹果,分类:笔记本','BACKEND');

INSERT INTO  biz_attribute (id,name,method,select_values) VALUES(0,'品牌','SELECT','华为,苹果,小米,三星');
INSERT INTO  biz_attribute (id,name,method,select_values) VALUES(1,'分类','SELECT','台式,平板,笔记本,手机,无线耳机,智能电视');
INSERT INTO  biz_attribute (id,name,method,select_values) VALUES(2,'屏幕尺寸','SELECT','60英尺,50英尺,40英尺');

INSERT INTO  product_detail (id,name,attributes,order_storage,actual_storage,sales,price,version) VALUES(0,'华为 P30Pro 64G','品牌:华为,分类:手机',100,100,0,3899.99,0);
INSERT INTO  product_detail (id,name,attributes,order_storage,actual_storage,sales,price,version) VALUES(1,'华为 P30Pro 128G','品牌:华为,分类:手机',100,100,0,3999.99,0);
INSERT INTO  product_detail (id,name,attributes,order_storage,actual_storage,sales,price,version) VALUES(2,'华为 matebook 128G','品牌:华为,分类:台式',100,100,0,6999.99,0);
INSERT INTO  product_detail (id,name,attributes,order_storage,actual_storage,sales,price,version) VALUES(3,'华为 matebook 256G','品牌:华为,分类:台式',100,100,0,7499.99,0);
INSERT INTO  product_detail (id,name,attributes,order_storage,actual_storage,sales,price,version) VALUES(4,'苹果 iphone11 64G','品牌:苹果,分类:手机',100,100,0,5699.99,0);
INSERT INTO  product_detail (id,name,attributes,order_storage,actual_storage,sales,price,version) VALUES(5,'苹果 iphone11 128G','品牌:苹果,分类:手机',100,100,0,5899.99,0);
INSERT INTO  product_detail (id,name,attributes,order_storage,actual_storage,sales,price,version) VALUES(6,'苹果 earpods','品牌:苹果,分类:无线耳机',100,100,0,1899.99,0);
INSERT INTO  product_detail (id,name,attributes,order_storage,actual_storage,sales,price,version) VALUES(7,'苹果 macbook','品牌:苹果,分类:笔记本',100,100,0,11899.99,0);
INSERT INTO  product_detail (id,name,attributes,order_storage,actual_storage,sales,price,version) VALUES(8,'苹果 macbook pro','品牌:苹果,分类:笔记本',100,100,0,15899.99,0);

